### ISSUE TITLE
Filter does not detect already set joins

### ISSUE THREAD

**Issue by Kreshnik** [aginev/search-filters#1]
Hi,

First of all, great package it has been helping for a while now.

For the first time now, I have encountered an issue. The issue is as following;

When the eloquent objects already calls join() and also a filter uses the same join, there is an error thrown, this is due to the fact that the join already exists. So it would be great if the package could detect that and remove the duplicate join, or not add it at all.

I hope the above is clear, if not please let me know.

Best,
Kreshnik

**Comment by aginev** [comment]
Hello Kreshnik,

Please submit code samples to take a look.

BR

**Comment by Kreshnik** [comment]
Hi Aginev, yes, of course. 

The following custom filter;

```
->custom('order', function ($query, $key, $value) {
	return $query->join('gig_details','gigs.id','=','gig_details.gig_id')->orderBy('gig_details.start_date', $value)->orderBy('gig_details.start_time', $value);
});
``` 

Will cause an error in the following case.

```
$model->filter($filters)->join('gig_details', 'gigs.id', '=', 'gig_details.gig_id');
```
Do you need more details?

**Comment by aginev** [comment]
The purpose of filters is limit and order the result set not to adding joins. Consider adding the join part to your main query then into the custom filter anonymous handler method. In fact I'm using it with joins but has some tricky parts

```php
$orders = $orderModel
    ->select(
        'orders.*',
        'statuses.order_id as status_order',
        DB::raw('(SELECT SUM(amount) FROM `balances` WHERE `balances`.`order_id` = `orders`.`id` GROUP BY `balances`.`order_id`) as `balance`')
    )
    ->leftJoin('statuses', 'orders.status_id', '=', 'statuses.id')
    ->with(['orderProducts', 'tags', 'status'])
    ->filter($request->input('f', []))
    ->orderBy('status_order', 'asc')
    ->orderBy('orders.updated_at', 'desc')
    ->paginate(Pagination::getPerPage());
```
Then the filter method inside the model

```php
/**
 * Set query filters
 *
 * Overwrite this method in the model to set query filters
 */
public function setFilters()
{
    $this->filter
        ->equal('id')
        ->equal('status_id')

        ...

        ->custom('status_order', function ($query, $key, $value) {
            $query->where('statuses.order_id', '=', $value);
        })

        ...

        ->custom('created_at', function ($query, $key, $value) {
            $query->where(\DB::raw('DATE(' . $key . ')'), '=', $value);
        })
        ->custom('updated_at', function ($query, $key, $value) {
            $query->where(\DB::raw('DATE(' . $key . ')'), '=', $value);
        }));
}
```

Note that:
1. Filtering based on joined table should be made with ```statuses.order_id``` not by the aliased ```status_order``` because of the way laravel handles pagination (note the ```count(*)```)

```
select count(*) as aggregate from `orders` left join `statuses` on `orders`.`status_id` = `statuses`.`id` where `orders`.`deleted_at` is null
```
2. For more advanced cases you can always use SQL VIEW and you'll have all the data you need into the view

**Comment by Kreshnik** [comment]
Thank you for the explanation Aginev, I will take that into account from now on. Thanks for taking the time.
